### ISSUE TITLE
Meaning of columns in sample info file

### ISSUE THREAD

**Issue by abayega** [Teichlab/SpatialDE#5]
Hi,

for the Frog dataset and specifically in the Frog_sample_info.csv, what is the meaning of ERCC and num_genes columns?

Also, did you manage to get an R version?

Thanks

**Comment by vals** [comment]
Hey,

The ERCC column is the relative expression of all the ERCC spike-ins. In the original paper by Owens et al this is used to infer total RNA abundance from each frog embryo.

The num_genes column is the number of unique genes were detected as expressed. I used it as a proxy for sequencing depth and regressed it out, because these are often correlated.

Regarding the R version, I am still working on it, I hope to make a Bioconductor version. I have had to work on some other things related to my recent move to Caltech though so it's been a bit sidetracked lately. I hope to continue on it shortly.

/Valentine
